cms/urls.py
from django.urls import path
from .views import PageView

app_name = 'cms'

urlpatterns = [
    path('<str:page_slug>', PageView.as_view(), name='page')
]

online/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('cms/', include('cms.urls')),
                  path('', include('shop_ecommerce.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  url(r'^auth/', include('social_django.urls', namespace='social')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_ecommerce/urls.py
from django.urls import path
from .views import *

app_name = 'shop_ecommerce'

urlpatterns = [
    path('', HomePage.as_view(), name='index'),
    path('search', SearchView.as_view(), name='search'),
    path('subcategory/<str:sub_slug>', SubCategoryView.as_view(), name='sub_wise'),
    path('product/', AllProduct.as_view(), name='product_wise'),
    path('singleproduct/<str:single_slug>', SingleProduct.as_view(), name='single'),
    path('register', SignUpView.as_view(), name='register'),
    path('cart', CartView.as_view(), name='cart'),
    path('checkout', CheckoutView.as_view(), name='checkout'),
    path('rem', RemoveCartView.as_view(), name='remove'),
    path('product/<str:slug>/', BrandView.as_view(), name='brand_wise'),

]

templates/partials/aside_widgets.html
{% load thumbnail %}
{% load app_filters %}


<!-- ASIDE -->
                <div id="aside" class="col-md-3">
                    <!-- aside widget -->
{#                    <div class="aside">#}
{#                        <h3 class="aside-title">Shop by:</h3>#}
{#                        <ul class="filter-list">#}
{#                            <li><span class="text-uppercase">color:</span></li>#}
{#                            <li><a href="#" style="color:#FFF; background-color:#8A2454;">Camelot</a></li>#}
{#                            <li><a href="#" style="color:#FFF; background-color:#475984;">East Bay</a></li>#}
{#                            <li><a href="#" style="color:#FFF; background-color:#BF6989;">Tapestry</a></li>#}
{#                            <li><a href="#" style="color:#FFF; background-color:#9A54D8;">Medium Purple</a></li>#}
{#                        </ul>#}
{##}
{#                        <ul class="filter-list">#}
{#                            <li><span class="text-uppercase">Size:</span></li>#}
{#                            <li><a href="#">X</a></li>#}
{#                            <li><a href="#">XL</a></li>#}
{#                        </ul>#}
{##}
{#                        <ul class="filter-list">#}
{#                            <li><span class="text-uppercase">Price:</span></li>#}
{#                            <li><a href="#">MIN: $20.00</a></li>#}
{#                            <li><a href="#">MAX: $120.00</a></li>#}
{#                        </ul>#}
{##}
{#                        <ul class="filter-list">#}
{#                            <li><span class="text-uppercase">Gender:</span></li>#}
{#                            <li><a href="#">Men</a></li>#}
{#                        </ul>#}
{##}
{#                        <button class="primary-btn">Clear All</button>#}
{#                    </div>#}
                    <!-- /aside widget -->

                    <!-- aside widget -->
                    <div class="aside">
                        <h3 class="aside-title">Filter by Price</h3>

                        {% for price in prices %}
                            <div id="price-slider"><a href="{% url 'shop_ecommerce:brand_wise' price %}">{{price}}</a></div>
                            {% endfor %}
                    </div>
                    <!-- aside widget -->

                    <!-- aside widget -->
{#                    <div class="aside">#}
{#                        <h3 class="aside-title">Filter By Color:</h3>#}
{#                        <ul class="color-option">#}
{#                            <li><a href="#" style="background-color:#475984;"></a></li>#}
{#                            <li><a href="#" style="background-color:#8A2454;"></a></li>#}
{#                            <li class="active"><a href="#" style="background-color:#BF6989;"></a></li>#}
{#                            <li><a href="#" style="background-color:#9A54D8;"></a></li>#}
{#                            <li><a href="#" style="background-color:#675F52;"></a></li>#}
{#                            <li><a href="#" style="background-color:#050505;"></a></li>#}
{#                            <li><a href="#" style="background-color:#D5B47B;"></a></li>#}
{#                        </ul>#}
{#                    </div>#}
                    <!-- /aside widget -->

                    <!-- aside widget -->
{#                    <div class="aside">#}
{#                        <h3 class="aside-title">Filter By Size:</h3>#}
{#                        <ul class="size-option">#}
{#                            <li class="active"><a href="#">S</a></li>#}
{#                            <li class="active"><a href="#">XL</a></li>#}
{#                            <li><a href="#">SL</a></li>#}
{#                        </ul>#}
{#                    </div>#}
                    <!-- /aside widget -->

                    <!-- aside widget -->
                    <div class="aside">
                        <h3 class="aside-title">Filter by Brand</h3>
                        <ul class="list-links">
                            {% for brand in brands %}
                            <li><a href="{% url 'shop_ecommerce:brand_wise' brand %}">{{brand}}</a></li>
                            {% endfor %}

                        </ul>
                    </div>
                    <!-- /aside widget -->

                    <!-- aside widget -->
{#                    <div class="aside">#}
{#                        <h3 class="aside-title">Filter by Gender</h3>#}
{#                        <ul class="list-links">#}
{#                            <li class="active"><a href="#">Men</a></li>#}
{#                            <li><a href="#">Women</a></li>#}
{#                        </ul>#}
{#                    </div>#}
                    <!-- /aside widget -->

                    <!-- aside widget -->
                    <div class="aside">
                        <h3 class="aside-title">Top Rated Product</h3>
                        <!-- widget product -->
                    {% for naya in toprated %}
                        <div class="product product-widget">
                            <div class="product-thumb">
                                {% thumbnail naya.image.image "345x455" crop="center" as im %}
                                    <img src="{{ im.url }}" alt="">
                                {% endthumbnail %}
                            </div>
                            <div class="product-body">
                                <h2 class="product-name"><a
                                        href="{% url 'shop_ecommerce:single' naya.slug %}">{{ naya.title }}</a></h2>
                                <h3 class="product-price">Rs. {{ naya.price }}
                                    <del class="product-old-price">RS. {{ naya.discount }}</del>
                                </h3>
                                <div class="product-rating">
                                    {% for i in naya.avg_rating|range %}
                                        <i class="fa fa-star"></i>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                        <!-- /widget product -->


                    </div>
                    <!-- /aside widget -->
                </div>
                <!-- /ASIDE -->