cms/urls.py
from django.urls import path
from .views import PageView

app_name = 'cms'

urlpatterns = [
    path('<str:page_slug>', PageView.as_view(), name='page')
]

online/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('cms/', include('cms.urls')),
                  path('', include('shop_ecommerce.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  url(r'^auth/', include('social_django.urls', namespace='social')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_ecommerce/urls.py
from django.urls import path
from .views import *

app_name = 'shop_ecommerce'

urlpatterns = [
    path('', HomePage.as_view(), name='index'),
    path('search', SearchView.as_view(), name='search'),
    path('subcategory/<str:sub_slug>', SubCategoryView.as_view(), name='sub_wise'),
    path('product/', AllProduct.as_view(), name='product_wise'),
    path('singleproduct/<str:single_slug>', SingleProduct.as_view(), name='single'),
    path('register', SignUpView.as_view(), name='register'),
    path('cart', CartView.as_view(), name='cart'),
    path('checkout', CheckoutView.as_view(), name='checkout'),
    path('rem', RemoveCartView.as_view(), name='remove'),
    path('product/<str:slug>/', BrandView.as_view(), name='brand_wise'),

]

templates/all_product.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% load app_filters %}
{% block content %}
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'shop_ecommerce:index' %}">Home</a></li>
                <li class="active">Products</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->

    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">

                {% include 'partials/aside_widgets.html' %}


                <!-- MAIN -->
                <div id="main" class="col-md-9">
                    <!-- store top filter -->
                    <div class="store-filter clearfix">
                        <div class="pull-left">
                            <div class="row-filter">
                                <a href="#"><i class="fa fa-th-large"></i></a>
                                <a href="#" class="active"><i class="fa fa-bars"></i></a>
                            </div>
                            <div class="sort-filter">
                                <span class="text-uppercase">Sort By:</span>
                                <select class="input">
                                    <option value="0">Position</option>
                                    <option value="0">Price</option>
                                    <option value="0">Rating</option>
                                </select>
                                <a href="#" class="main-btn icon-btn"><i class="fa fa-arrow-down"></i></a>
                            </div>
                        </div>

                    </div>
                    <!-- /store top filter -->

                    <!-- STORE -->
                    <div id="store">
                        <!-- row -->
                        <div class="row">
                            <!-- Product Single -->
                            {% for product in allproduct_pages %}

                                <div class="col-md-4 col-sm-6 col-xs-6">
                                    <div class="product product-single">
                                        <div class="product-thumb">

                                            <button class="main-btn quick-view"><i class="fa fa-search-plus"></i><a
                                                    href="{% url 'shop_ecommerce:single' product.slug %}"> Quick
                                                view</a>
                                            </button>

                                            {% thumbnail product.image.image "262x350" crop="center" as im %}
                                                <img src="{{ im.url }}" alt="">
                                            {% endthumbnail %}
                                        </div>
                                        <div class="product-body">
                                            <h3 class="product-price">Rs. {{ product.price }}
                                                <del class="product-old-price">{{ product.discount }}</del>
                                            </h3>
                                            <div class="product-rating">
                                                {% for i in product.avg_rating|range %}
                                        <i class="fa fa-star"></i>
                                    {% endfor %}
                                            </div>
                                            <h2 class="product-name"><a
                                                    href="{% url 'shop_ecommerce:single' product.slug %}">{{ product.title }}</a>
                                            </h2>
{#                                            <div class="product-btns">#}
{#                                                <button class="main-btn icon-btn"><i class="fa fa-heart"></i>#}
{#                                                </button>#}
{#                                                <button class="main-btn icon-btn"><i class="fa fa-exchange"></i>#}
{#                                                </button>#}
{#                                                <button class="primary-btn add-to-cart"><i#}
{#                                                        class="fa fa-shopping-cart"></i>#}
{#                                                    Add to Cart#}
{#                                                </button>#}
{#                                            </div>#}
                                        </div>
                                    </div>
                                </div>
                                <!-- /Product Single -->

                            {% endfor %}

                        </div>
                        <!-- /row -->
                    </div>
                    <!-- /STORE -->

                    <!-- store bottom filter -->
                    <div class="store-filter clearfix">

                        <div class="pull-right">
                            <ul class="store-pages">
                                <li><span class="text-uppercase">Page:</span></li>

                                <li>
                                    {% if allproduct_pages.has_previous %}
                                        <a href="?page={{ allproduct_pages.previous_page_number }}"
                                           aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    {% endif %}
                                </li>
                                {% for page in paginator.page_range %}
                                    <li><a href="?page={{ page }}">{{ page }}</a></li>
                                {% endfor %}
                                <li>
                                    {% if allproduct_pages.has_next %}
                                        <a href="?page={{ allproduct_pages.next_page_number }}" aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    {% endif %}
                                </li>

                            </ul>
                        </div>
                    </div>
                    <!-- /store bottom filter -->
                </div>
                <!-- /MAIN -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
{% endblock %}

templates/cart.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}

    <div class="col-md-12">
        <div class="order-summary clearfix">
            <div class="section-title">
                <h3 class="title">Order Review</h3>
            </div>
            <table class="shopping-cart-table table">
                <thead>
                <tr>
                    <th>Product</th>
                    <th></th>
                    <th class="text-center">Price</th>
                    <th class="text-center">Quantity</th>
                    <th class="text-center">Total</th>
                    <th class="text-right"></th>
                </tr>
                </thead>
                <tbody>
                {% for cart in cart_items %}
                    <tr>
                        <td class="thumb">
                            {% thumbnail cart.product.image.image "60x60" crop="center" as im %}
                                <img src="{{ im.url }}">
                            {% endthumbnail %}
                        </td>
                        <td class="details">
                            <a href="#">{{ cart.product.title }}</a>
                            <ul>
                                <li><span>Size: XL</span></li>
                                <li><span>Color: Camelot</span></li>
                            </ul>
                        </td>
                        <td class="price text-center"><strong>Rs. {{ cart.product.price }}</strong><br>
                            <del class="font-weak">
                                <small>$40.00</small>
                            </del>
                        </td>
                        <td class="qty text-center"><input class="input" type="number" value="{{ cart.qty }}"></td>
                        <td class="total text-center"><strong class="primary-color">Rs. {{ cart.total }}</strong></td>
                        <td class="text-right">
                            <form method="post" action="{% url 'shop_ecommerce:remove' %}">
                                {% csrf_token %}
                                <input type="hidden" value="{{ cart.id }}" name="id">
                                <button class="main-btn icon-btn"><i class="fa fa-close"></i></button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <th class="empty" colspan="3"></th>
                    <th>SUBTOTAL</th>
                    <th colspan="2" class="sub-total">Rs. {{ total_amount }}</th>
                </tr>
                <tr>
                    <th class="empty" colspan="3"></th>
                    <th>SHIPING</th>
                    <td colspan="2">Free Shipping</td>
                </tr>
                <tr>
                    <th class="empty" colspan="3"></th>
                    <th>TOTAL</th>
                    <th colspan="2" class="total">$97.50</th>
                </tr>
                </tfoot>
            </table>
            <div class="pull-right">
                <button class="primary-btn"><a href="{% url 'shop_ecommerce:checkout' %}">Check Out</a></button>
            </div>
        </div>

    </div>

{% endblock %}

templates/checkout.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}



    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <form id="checkout-form" class="clearfix">
                    <div class="col-md-6">
                        <div class="billing-details">
                            <p>Already a customer ? <a href="#">Login</a></p>
                            <div class="section-title">
                                <h3 class="title">Billing Details</h3>
                            </div>
                            <div class="form-group">
                                <input class="input" type="text" name="first-name" placeholder="First Name">
                            </div>
                            <div class="form-group">
                                <input class="input" type="text" name="last-name" placeholder="Last Name">
                            </div>
                            <div class="form-group">
                                <input class="input" type="email" name="email" placeholder="Email">
                            </div>
                            <div class="form-group">
                                <input class="input" type="text" name="address" placeholder="Address">
                            </div>
                            <div class="form-group">
                                <input class="input" type="text" name="city" placeholder="City">
                            </div>
                            <div class="form-group">
                                <input class="input" type="text" name="country" placeholder="Country">
                            </div>
                            <div class="form-group">
                                <input class="input" type="text" name="zip-code" placeholder="ZIP Code">
                            </div>
                            <div class="form-group">
                                <input class="input" type="tel" name="tel" placeholder="Telephone">
                            </div>
                            <div class="form-group">
                                <div class="input-checkbox">
                                    <input type="checkbox" id="register">
                                    <label class="font-weak" for="register">Create Account?</label>
                                    <div class="caption">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                            tempor incididunt.
                                        <p>
                                            <input class="input" type="password" name="password"
                                                   placeholder="Enter Your Password">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="shiping-methods">
                            <div class="section-title">
                                <h4 class="title">Shiping Methods</h4>
                            </div>
                            <div class="input-checkbox">
                                <input type="radio" name="shipping" id="shipping-1" checked>
                                <label for="shipping-1">Free Shiping - $0.00</label>
                                <div class="caption">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                                        nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                    <p>
                                </div>
                            </div>
                            <div class="input-checkbox">
                                <input type="radio" name="shipping" id="shipping-2">
                                <label for="shipping-2">Standard - $4.00</label>
                                <div class="caption">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                                        nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                    <p>
                                </div>
                            </div>
                        </div>

                        <div class="payments-methods">
                            <div class="section-title">
                                <h4 class="title">Payments Methods</h4>
                            </div>
                            <div class="input-checkbox">
                                <input type="radio" name="payments" id="payments-1" checked>
                                <label for="payments-1">Direct Bank Transfer</label>
                                <div class="caption">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                                        nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                    <p>
                                </div>
                            </div>
                            <div class="input-checkbox">
                                <input type="radio" name="payments" id="payments-2">
                                <label for="payments-2">Cheque Payment</label>
                                <div class="caption">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                                        nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                    <p>
                                </div>
                            </div>
                            <div class="input-checkbox">
                                <input type="radio" name="payments" id="payments-3">
                                <label for="payments-3">Paypal System</label>
                                <div class="caption">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                                        nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                    <p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="order-summary clearfix">
                            <div class="section-title">
                                <h3 class="title">Order Review</h3>
                            </div>
                            <table class="shopping-cart-table table">
                                <thead>
                                <tr>
                                    <th>Product</th>
                                    <th></th>
                                    <th class="text-center">Price</th>
                                    <th class="text-center">Quantity</th>
                                    <th class="text-center">Total</th>
                                    <th class="text-right"></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for acart in cart_itms %}
                                    <a href="{% url 'shop_ecommerce:single' acart.product.slug %}"></a>
                                    <tr>
                                        <td class=" thumb">
                                    {% thumbnail acart.product.image.image "60x60" crop="center" as im %}
                                        <img src="{{ im.url }}">
                                    {% endthumbnail %}
                                    </td>
                                    <td class="details">
                                        <a href="#">{{ acart.product.title }}</a>
                                        <ul>
                                            <li><span>Size: XL</span></li>
                                            <li><span>Color: Camelot</span></li>
                                        </ul>
                                    </td>
                                    <td class="price text-center"><strong>Rs. {{ acart.product.price }}</strong><br>
                                        <del class="font-weak">
                                            <small>$40.00</small>
                                        </del>
                                    </td>
                                    <td class="qty text-center"><input class="input" type="number" value="{{ acart.qty }}"></td>
                                    <td class="total text-center"><strong
                                            class="primary-color">{{ acart.total }}</strong></td>

                                    </tr>
                                {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th class="empty" colspan="3"></th>
                                    <th>SUBTOTAL</th>
                                    <th colspan="2" class="sub-total">Rs. {{ total_amount }}</th>
                                </tr>
                                <tr>
                                    <th class="empty" colspan="3"></th>
                                    <th>SHIPING</th>
                                    <td colspan="2">Free Shipping</td>
                                </tr>
                                <tr>
                                    <th class="empty" colspan="3"></th>
                                    <th>TOTAL</th>
                                    <th colspan="2" class="total">$97.50</th>
                                </tr>
                                </tfoot>
                            </table>
                            <div class="pull-right">
                                <button class="primary-btn"><a href="{% url 'shop_ecommerce:checkout' %}">Place
                                    Order</a></button>
                            </div>
                        </div>

                    </div>
                </form>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}

    <div class="col-12">


            <div class="product product-single">
                <div class="product-thumb">
                    <h2 class="product-name"><a href="#">{{ page.title }}</a></h2>

                    {% thumbnail page.image "1163x365" crop="center" as im %}
                        <img src="{{ im.url }}" alt="">
                    {% endthumbnail %}

                </div>


            </div>
            <div class="product-body">

                <h2 class="product-name"><a href="#">{{ page.content }}</a></h2>
            </div>



    </div>


{% endblock %}

templates/products.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% load app_filters %}
{% block content %}
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="#">Home</a></li>
                <li class="active">Products</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->

    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                {% include 'partials/aside_widgets.html' %}

                <!-- MAIN -->
                <div id="main" class="col-md-9">
                    <!-- store top filter -->
                    <div class="store-filter clearfix">
                        <div class="pull-left">
                            <div class="row-filter">
                                <a href="#"><i class="fa fa-th-large"></i></a>
                                <a href="#" class="active"><i class="fa fa-bars"></i></a>
                            </div>
                            <div class="sort-filter">
                                <span class="text-uppercase">Sort By:</span>
                                <select class="input">
                                    <option value="0">Position</option>
                                    <option value="0">Price</option>
                                    <option value="0">Rating</option>
                                </select>
                                <a href="#" class="main-btn icon-btn"><i class="fa fa-arrow-down"></i></a>
                            </div>
                        </div>
                    </div>
                    <!-- /store top filter -->

                    <!-- STORE -->
                    <div id="store">
                        <!-- row -->
                        <div class="row">
                            <!-- Product Single -->
                            {% for product in subcategory_pages %}

                                <div class="col-md-4 col-sm-6 col-xs-6">
                                    <div class="product product-single">
                                        <div class="product-thumb">

                                            <button class="main-btn quick-view"><i class="fa fa-search-plus"></i>
                                                <a href="{% url 'shop_ecommerce:single' product %}"> Quick view</a>
                                            </button>

                                            {% thumbnail product.image.image "252x350" crop="center" as im %}
                                                <img src="{{ im.url }}" alt="">
                                            {% endthumbnail %}
                                        </div>
                                        <div class="product-body">
                                            <h3 class="product-price">Rs. {{ product.price }}
                                                <del class="product-old-price">{{ product.discount }}</del>
                                            </h3>
                                            <div class="product-rating">
                                               {% for i in product.avg_rating|range %}
                                        <i class="fa fa-star"></i>
                                    {% endfor %}
                                            </div>
                                            <h2 class="product-name"><a
                                                    href="{% url 'shop_ecommerce:single' product %}">{{ product.title }}</a></h2>
{#                                            <div class="product-btns">#}
{#                                                <button class="main-btn icon-btn"><i class="fa fa-heart"></i>#}
{#                                                </button>#}
{#                                                <button class="main-btn icon-btn"><i class="fa fa-exchange"></i>#}
{#                                                </button>#}
{#                                                <button class="primary-btn add-to-cart"><i#}
{#                                                        class="fa fa-shopping-cart"></i>#}
{#                                                    Add to Cart#}
{#                                                </button>#}
{#                                            </div>#}
                                        </div>
                                    </div>
                                </div>
                                <!-- /Product Single -->

                            {% endfor %}

                        </div>
                        <!-- /row -->
                    </div>
                    <!-- /STORE -->

                    <!-- store bottom filter -->
                    <div class="store-filter clearfix">

                        <div class="pull-right">
                            <ul class="store-pages">
                                <li><span class="text-uppercase">Page:</span></li>

                                <li>
                                    {% if subcategory_pages.has_previous %}
                                        <a href="?page={{ subcategory_pages.previous_page_number }}" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    {% endif %}
                                </li>
                                {% for page in paginator.page_range %}
                                    <li><a href="?page={{ page }}">{{ page }}</a></li>
                                {% endfor %}
                                <li>
                                    {% if subcategory_pages.has_next %}
                                        <a href="?page={{ subcategory_pages.next_page_number }}" aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    {% endif %}
                                </li>

                            </ul>
                        </div>
                        </div>
                    </div>
                    <!-- /store bottom filter -->
                </div>
                <!-- /MAIN -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
{% endblock %}